AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: web-site-checker

Globals:
  Function:
    Timeout: 30
    MemorySize: 256

Parameters:
  Env:
    Type: String

Resources:
  WebSiteCheckerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${Env}-web-site-checker-function"
      CodeUri: web_site_checker/
      Handler: app.WebSiteChecker::Handler.process
      Runtime: ruby3.2
      Architectures:
        - x86_64
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt WebSiteCheckerHistoryTable.Arn
            - Effect: Allow
              Action:
                - sns:Publish
              Resource:
                - !GetAtt WebSiteCheckerNotificationTopic.TopicArn

  WebSiteCheckerHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${Env}-web-site-checker-history"
      KeySchema:
        - AttributeName: url
          KeyType: HASH
        - AttributeName: xpath
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
        - AttributeName: xpath
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  WebSiteCheckerNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${Env}-web-site-checker-notification"
      DisplayName: !Sub "${Env}-web-site-checker-notification"

Outputs:
  WebSiteCheckerFunction:
    Description: "Web Site Checker Lambda Function ARN"
    Value: !GetAtt WebSiteCheckerFunction.Arn
  WebSiteCheckerFunctionRole:
    Description: "Web Site Checker Lambda Function Role ARN"
    Value: !GetAtt WebSiteCheckerFunctionRole.Arn
  WebSiteCheckerHistoryTable:
    Description: "History Table ARN"
    Value: !GetAtt WebSiteCheckerHistoryTable.Arn
  WebSiteCheckerNotificationTopic:
    Description: "Notification Topic ARN"
    Value: !GetAtt WebSiteCheckerNotificationTopic.TopicArn
